{% set version = "1.6.4" %}

package:
  name: property-cached
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/property-cached/property-cached-{{ version }}.zip
  sha256: 3e9c4ef1ed3653909147510481d7df62a3cfb483461a6986a6f1dcd09b2ebb73

build:
  number: 0

outputs:
  - name: property-cached
    script: build_base.bat  # [win]
    script: build_base.sh  # [not win]
    build:
      noarch: python
    requirements:
      host:
        - python
        - pip
        - setuptools >=39.2
      run:
        - python
        - setuptools >=39.2
    test:
      requires:
        - pip
      commands:
        - pip check
      imports:
        - property_cached

  - name: property_cached
    build:
      noarch: generic
    requirements:
      run:
        - {{ pin_subpackage('property-cached', max_pin="x.x.x") }}
    test:
      imports:
        - property_cached

about:
  home: https://github.com/althonos/property-cached/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A decorator for caching properties in classes (forked from cached-property).

extra:
  recipe-maintainers:
    - ocefpaf
